import { Appointment } from './appointments';

export const SEED_PATIENTS: Omit<Appointment, 'id' | 'created_at'>[] = [
  {
    name: 'Fatima Zahra Bennani',
    phone: '0661234501',
    email: 'fz.bennani@gmail.com',
    service: 'Suivi de grossesse',
    preferred_date: '2025-01-15',
    message: "Première grossesse, 8 semaines d'aménorrhée.",
    status: 'done',
    source: 'web',
    notes: 'Grossesse bien évoluée. Prochain RDV à 12 SA.',
  },
  {
    name: 'Khadija El Amrani',
    phone: '0662345602',
    email: null,
    service: 'Echographie 3D-4D',
    preferred_date: '2025-01-22',
    message: 'Souhaite une échographie morphologique.',
    status: 'done',
    source: 'whatsapp',
    notes: 'Morphologie normale. Sexe non demandé.',
  },
  {
    name: 'Zineb Oukili',
    phone: '0663456703',
    email: 'zineb.oukili@hotmail.com',
    service: 'Stérilité du couple',
    preferred_date: '2025-01-28',
    message: '3 ans sans grossesse. Bilan de fertilité souhaité.',
    status: 'confirmed',
    source: 'web',
    notes: 'Bilan hormonal prescrit. RDV de suivi prévu.',
  },
  {
    name: 'Nadia Cherif',
    phone: '0664567804',
    email: 'n.cherif@yahoo.fr',
    service: 'Gynécologie médicale',
    preferred_date: '2025-02-03',
    message: 'Douleurs pelviennes depuis 2 semaines.',
    status: 'done',
    source: 'web',
    notes: null,
  },
  {
    name: 'Hafsa Moussaoui',
    phone: '0665678905',
    email: null,
    service: 'Colposcopie',
    preferred_date: '2025-02-10',
    message: 'Frottis anormal, adressée par son médecin traitant.',
    status: 'done',
    source: 'whatsapp',
    notes: 'Colposcopie normale. Contrôle dans 6 mois.',
  },
  {
    name: 'Samira Tahiri',
    phone: '0666789006',
    email: 'samira.tahiri@gmail.com',
    service: 'Accouchement',
    preferred_date: '2025-02-14',
    message: 'Suivi de fin de grossesse, terme prévu fin février.',
    status: 'done',
    source: 'web',
    notes: 'Accouchement voie basse. Bonne récupération.',
  },
  {
    name: 'Loubna Idrissi',
    phone: '0667890107',
    email: 'loubna.idrissi@gmail.com',
    service: 'Chirurgie cœlioscopique',
    preferred_date: '2025-02-20',
    message: "Kyste ovarien diagnostiqué à l'échographie.",
    status: 'confirmed',
    source: 'web',
    notes: 'Kyste de 4cm. Intervention programmée.',
  },
  {
    name: 'Imane Bakkali',
    phone: '0668901208',
    email: null,
    service: 'Troubles sexuels',
    preferred_date: '2025-02-25',
    message: null,
    status: 'done',
    source: 'whatsapp',
    notes: 'Consultation confidentielle. Suivi proposé.',
  },
  {
    name: 'Soukaina Rahali',
    phone: '0669012309',
    email: 'soukaina.r@gmail.com',
    service: 'Suivi de grossesse',
    preferred_date: '2025-03-04',
    message: 'Grossesse de 20 SA, suivi régulier.',
    status: 'confirmed',
    source: 'web',
    notes: null,
  },
  {
    name: 'Meryem Benali',
    phone: '0661123410',
    email: 'meryem.benali@gmail.com',
    service: 'Echographie 3D-4D',
    preferred_date: '2025-03-08',
    message: 'Echographie de contrôle à 32 SA.',
    status: 'pending',
    source: 'web',
    notes: null,
  },
  {
    name: 'Houda Tazi',
    phone: '0662234511',
    email: null,
    service: 'Chirurgie du sein',
    preferred_date: '2025-03-12',
    message: 'Masse palpable sein gauche depuis 1 mois.',
    status: 'confirmed',
    source: 'whatsapp',
    notes: 'Échographie mammaire réalisée. Biopsie programmée.',
  },
  {
    name: 'Asmae El Fassi',
    phone: '0663345612',
    email: 'asmae.elfassi@hotmail.com',
    service: 'Hystéroscopie',
    preferred_date: '2025-03-18',
    message: 'Saignements irréguliers depuis 3 mois.',
    status: 'pending',
    source: 'web',
    notes: null,
  },
  {
    name: 'Rabia Ouazzani',
    phone: '0664456713',
    email: null,
    service: 'Gynécologie médicale',
    preferred_date: '2025-03-22',
    message: 'Renouvellement contraceptif et bilan annuel.',
    status: 'pending',
    source: 'web',
    notes: null,
  },
  {
    name: 'Chaima Alaoui',
    phone: '0665567814',
    email: 'chaima.alaoui@gmail.com',
    service: 'Stérilité du couple',
    preferred_date: '2025-03-27',
    message: 'Deuxième consultation. Résultats du bilan reçus.',
    status: 'pending',
    source: 'web',
    notes: null,
  },
  {
    name: 'Sara Mansouri',
    phone: '0666678915',
    email: 'sara.mansouri@yahoo.fr',
    service: 'Chirurgie gynécologique',
    preferred_date: '2025-04-02',
    message: 'Fibrome utérin symptomatique.',
    status: 'pending',
    source: 'whatsapp',
    notes: null,
  },
  {
    name: 'Nour El Houda Filali',
    phone: '0667789016',
    email: null,
    service: 'Colposcopie',
    preferred_date: '2025-04-07',
    message: null,
    status: 'cancelled',
    source: 'web',
    notes: 'Patiente annulé par téléphone.',
  },
  {
    name: 'Yasmine Berrada',
    phone: '0668890117',
    email: 'yasmine.berrada@gmail.com',
    service: 'Chirurgie du cancer',
    preferred_date: '2025-04-10',
    message: "Adressée par l'oncologue pour prise en charge chirurgicale.",
    status: 'confirmed',
    source: 'web',
    notes: "Dossier en cours. Coordination avec l'équipe oncologie.",
  },
  {
    name: 'Meriem Skalli',
    phone: '0669901218',
    email: 'meriem.skalli@gmail.com',
    service: 'Accouchement',
    preferred_date: '2025-04-15',
    message: 'Terme prévu le 20 avril. Pré-admission souhaitée.',
    status: 'pending',
    source: 'web',
    notes: null,
  },
];
